export const ROUTES = {
  INFO: "INFO",
  POLLUTION_CITIES: "POLLUTION_CITIES",
  HOME: "HOME",
  FORECAST_POLLUTION_FOR_THE_DAY: "FORECAST_POLLUTION_FOR_THE_DAY",
  MY_CITIES: "MY_CITIES",
  TURN_NOTICIFICATIONS: "TURN_NOTICIFICATIONS",
  OFFLINE: "OFFLINE",
};
