

export const STATE_KEYS = {
	IS_CHECK_INFO: 'IS_CHECK_INFO',
	IS_ALLOWED_PLACE: 'IS_ALLOWED_PLACE',
	DEFAULT_CITY_ID: 'DEFAULT_CITY_ID',
	DEFAULT_COUNTRY_NAME: 'DEFAULT_COUNTRY_NAME',
	DEFAULT_COUNTRY_ID: 'DEFAULT_COUNTRY_ID'
}